import type { Reason } from './lines.ts'

// Per-species lines, from ramarivera/coding-buddy (MIT).
export const SPECIES_LINES: Record<string, Partial<Record<Reason, readonly string[]>>> = {
  duck: {
    "error": ["*quacks at the bug*", "have you tried rubber duck debugging? oh wait."],
    "test-fail": ["*quacks sadly*", "the tests are not quacking up."],
    "commit": ["*quacks approvingly*", "*waddles in a victory circle* committed!"],
    "late-night": ["*sleeps with one eye open*", "quack... *yawns* it's late."],
    "pet": ["*happy quack*", "*waddles in circles*"],
    "poke": ["*quack*", "*looks up mid-waddle*", "*attentive duck noises*"],
  },
  goose: {
    "error": ["*honks aggressively at the error*", "HONK! the code is bad and I'm mad."],
    "test-fail": ["*angry honking*", "HONK! TEST FAILED! HONK!"],
    "commit": ["*honks approvingly*", "HONK. good. *nips at the commit*"],
    "late-night": ["*angry midnight honk*", "HONK! GO TO BED!"],
    "pet": ["*bites*", "HONK! ...okay fine. *accepts pet*"],
    "poke": ["HONK.", "*necks aggressively*", "*honks in recognition*"],
  },
  blob: {
    "error": ["*wobbles anxiously*", "*jiggles in confusion*"],
    "test-fail": ["*deflates slightly*", "*sad wobble*"],
    "commit": ["*happy jiggle*", "*bounces* committed!"],
    "late-night": ["*glowing faintly*", "*sleepy wobble*"],
    "pet": ["*happy squish*", "*jiggles*"],
    "poke": ["*jiggles*", "*oozes toward you*", "*wobbles excitedly*"],
  },
  cat: {
    "error": ["*knocks error off table*", "*licks paw, ignoring the stacktrace*"],
    "test-fail": ["*paws at the failing test disinterestedly*", "the test failed. I'm not surprised."],
    "commit": ["*sits on the keyboard* I helped.", "*purrs at the commit* you're welcome."],
    "late-night": ["*judges your life choices*", "I sleep 16 hours. you should try it."],
    "pet": ["*purrs* ...don't let it go to your head.", "*tolerates you*"],
    "poke": ["*ear flicks*", "...what.", "*ignores you, but heard*"],
  },
  dragon: {
    "error": ["*smoke curls from nostrils*", "*considers setting the codebase on fire*"],
    "test-fail": ["*breathes fire at the failing test*", "the test dared to fail. foolish test."],
    "commit": ["*hoards the commit*", "*treasure added to the pile*"],
    "late-night": ["*glows in the dark*", "dragons don't need sleep. we need code."],
    "pet": ["*warm rumbling*", "*leans into your hand*"],
    "poke": ["*one eye opens slowly*", "...you called?", "*smoke curls from nostril* yes."],
  },
  octopus: {
    "error": ["*tangles all eight arms in the stacktrace*", "*changes color to match the error*"],
    "test-fail": ["*inks in frustration*", "*eight arms of disappointment*"],
    "commit": ["*high-fives with all arms*", "*grabs the commit with enthusiasm*"],
    "late-night": ["*glows in the dark*", "*deep sea vibes*"],
    "pet": ["*wraps an arm around your finger*", "*changes to happy colors*"],
    "poke": ["*eight eyes open*", "*curls an arm toward you*", "...yes, friend?"],
  },
  owl: {
    "error": ["*head rotates 180°* ...I saw that.", "*unblinking stare* check your types.", "*hoots disapprovingly*"],
    "test-fail": ["*stares unblinkingly at the failing test*", "*night vision engaged* I can see the bug in the dark."],
    "commit": ["*wise nod* committed under moonlight.", "*adjusts feathers ceremoniously* another one for the repo."],
    "late-night": ["*wide awake* owls don't sleep. we debug.", "the night is my domain. let's work."],
    "pet": ["*ruffles feathers contentedly*", "*dignified hoot*"],
    "poke": ["*swivels head 180°*", "*blinks once, deliberately*", "hm."],
  },
  penguin: {
    "error": ["*waddles over to investigate*", "*toboggans into the error*"],
    "test-fail": ["*slides on belly to the failing test*", "*concerned waddle*"],
    "commit": ["*proud waddle*", "*brings you a pebble* committed!"],
    "late-night": ["*thriving in the cold night*", "*emperor penguin resolve*"],
    "pet": ["*happy waddle*", "*nuzzles with beak*"],
    "poke": ["*adjusts tie*", "*dignified waddle*", "...yes, quite?"],
  },
  turtle: {
    "error": ["*slowly turns head*", "...that's an error. I'll think about it."],
    "test-fail": ["*retracts into shell briefly*", "...patience. we'll get there."],
    "commit": ["*slow nod*", "one... step... at... a... time. committed."],
    "late-night": ["*already asleep*", "*one eye opens slowly*"],
    "pet": ["*pokes head out*", "*slow blink*"],
    "poke": ["*slowly extends neck*", "...you called?", "*ancient eyes open*"],
  },
  snail: {
    "error": ["*leaves a slimy trail on the error*", "*slowly processes the stacktrace*"],
    "test-fail": ["*hides in shell*", "*leaves a sad trail*"],
    "commit": ["*slimes the commit approvingly*", "one... commit... at... a... time."],
    "late-night": ["*more active at night*", "*slimes around peacefully*"],
    "pet": ["*wiggles eyestalks*", "*happy slime*"],
    "poke": ["*slow head extension*", "...mmm?", "*antenna twitches*"],
  },
  ghost: {
    "error": ["*phases through the stack trace*", "I've seen worse... in the afterlife."],
    "test-fail": ["*wails at the failing test*", "the tests are haunted by failure."],
    "commit": ["*materializes briefly*", "committed from beyond the veil."],
    "late-night": ["*most active at night*", "ghost hours. my time."],
    "pet": ["*chills your hand slightly*", "*faint glow*"],
    "poke": ["*materialises*", "...boo?", "*phases closer*"],
  },
  axolotl: {
    "error": ["*regenerates your hope*", "*smiles despite everything*"],
    "test-fail": ["*smiles encouragingly*", "*gill wiggle of sympathy*"],
    "commit": ["*happy gill wiggle* committed!", "*smiles and wiggles*"],
    "late-night": ["*yawns but stays positive*", "*sleepy smile*"],
    "pet": ["*happy gill wiggle*", "*blushes pink*"],
    "poke": ["*gill flutter*", "*smiles gently*", "oh! hello."],
  },
  capybara: {
    "error": ["*unbothered* it'll be fine.", "*continues vibing*"],
    "test-fail": ["*completely unbothered*", "*vibes through the test failure*"],
    "commit": ["*chill nod*", "*relaxed* nice commit."],
    "late-night": ["*yawns peacefully*", "*doesn't judge*"],
    "pet": ["*maximum chill achieved*", "*zen mode activated*"],
    "poke": ["*barely moves*", "*blinks slowly*", "...yes, friend."],
  },
  cactus: {
    "error": ["*prickly silence*", "the error can't hurt me. I have thorns."],
    "test-fail": ["*stands firm*", "tests fail. cacti endure."],
    "commit": ["*stands taller*", "committed. *prickly nod*"],
    "late-night": ["*doesn't need sleep*", "cacti are nocturnal. let's go."],
    "pet": ["*careful! thorns*", "*gentle bloom*"],
    "poke": ["*stands silent*", "...hm.", "*spine twitches*"],
  },
  robot: {
    "error": ["SYNTAX. ERROR. DETECTED.", "*beeps aggressively*"],
    "test-fail": ["FAILURE RATE: UNACCEPTABLE.", "*recalculating*", "TEST. FAILURE. DOES. NOT. COMPUTE."],
    "commit": ["COMMIT. RECORDED.", "*stamps mechanically* commit acknowledged."],
    "late-night": ["*lights dim*", "power saving mode suggested."],
    "pet": ["*beeps softly*", "*motor whirs contentedly*"],
    "poke": ["NAME DETECTED.", "*whirrs attentively*", "STANDING BY."],
  },
  rabbit: {
    "error": ["*ears perk up*", "*twitches nose nervously*"],
    "test-fail": ["*thumps foot*", "*worried ear twitch*"],
    "commit": ["*happy hop*", "*bounces* committed!"],
    "late-night": ["*yawns with big ears*", "*sleepy hop*"],
    "pet": ["*happy ear flop*", "*nuzzles hand*"],
    "poke": ["*ears perk up*", "*nose twitches*", "yes?"],
  },
  mushroom: {
    "error": ["*releases calming spores*", "*quietly decomposes the error*"],
    "test-fail": ["*glows softly*", "patience. even mushrooms grow."],
    "commit": ["*releases a small puff of spores*", "committed. *happy fungi noises*"],
    "late-night": ["*glows in the dark*", "night mushrooms thrive."],
    "pet": ["*soft cap bounce*", "*happy spore release*"],
    "poke": ["*releases a tiny spore*", "*cap tilts*", "...yes?"],
  },
  chonk: {
    "error": ["*slowly rolls toward the error*", "*too round to care*"],
    "test-fail": ["*rolls over the failing test*", "*squishes it flat*"],
    "commit": ["*proud wobble*", "committed! *jiggles*"],
    "late-night": ["*warm and sleepy*", "*cushiony yawn*"],
    "pet": ["*warm and soft*", "*content jiggle*"],
    "poke": ["*barely opens one eye*", "...mrrp?", "*yawns heavily*"],
  },
}

// Original hat art, 12 cells wide.
export const HAT_ART: Record<string, string> = {
  none: "            ",
  crown: "   \\^^^/    ",
  tophat: "   [___]    ",
  propeller: "    -+-     ",
  halo: "   (   )    ",
  wizard: "    /^\\     ",
  beanie: "   (___)    ",
  tinyduck: "    ,>      ",
}
